repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^(frontend|backend)/.*\.(ts|tsx|js|jsx|css|scss|json|md)$
        additional_dependencies:
          - prettier@3.1.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      # Frontend ESLint
      - id: eslint
        name: eslint-frontend
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.57.1
          - eslint-config-next@14.2.16
          - typescript@5.7.3
          - '@typescript-eslint/eslint-plugin@8.20.0'
          - '@typescript-eslint/parser@8.20.0'

      # Backend ESLint
      - id: eslint
        name: eslint-backend
        files: ^backend/.*\.(js|ts)$
        types: [file]
        additional_dependencies:
          - eslint@8.57.1
          - '@typescript-eslint/eslint-plugin@8.20.0'
          - '@typescript-eslint/parser@8.20.0'
          - eslint-config-prettier@9.1.0
          - eslint-plugin-node@11.1.0
